package net.runelite.client.plugins.microbot.goon.mainHandler;

import java.util.List;

public class LootItemNames {
    public static final List<String> LOOT_ITEM_NAMES = List.of(
            "Burnt page",
            "Tome of fire (empty)",
            "Dragon axe",
            "Oak logs",
            "Willow logs",
            "Teak logs",
            "Maple logs",
            "Mahogany logs",
            "Yew logs",
            "Magic logs",
            "Uncut sapphire",
            "Uncut emerald",
            "Uncut ruby",
            "Uncut diamond",
            "Pure essence",
            "Limestone",
            "Silver ore",
            "Iron ore",
            "Coal",
            "Gold ore",
            "Mithril ore",
            "Adamantite ore",
            "Runite ore",
            "Grimy guam leaf",
            "Grimy marrentill",
            "Grimy tarromin",
            "Grimy harralander",
            "Grimy ranarr weed",
            "Grimy irit leaf",
            "Grimy avantoe",
            "Grimy kwuarm",
            "Grimy cadantine",
            "Grimy lantadyme",
            "Grimy dwarf weed",
            "Grimy torstol",
            "Maple seed",
            "Mahogany seed",
            "Yew seed",
            "Ranarr seed",
            "Toadflax seed",
            "Avantoe seed",
            "Kwuarm seed",
            "Snapdragon seed",
            "Cadantine seed",
            "Dwarf weed seed",
            "Watermelon seed",
            "Snape grass seed",
            "Magic seed",
            "Torstol seed",
            "Raw tuna",
            "Raw lobster",
            "Raw swordfish",
            "Raw shark",
            "Dynamite"
    );
}
